[package]
name = "Spider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = {version = "2.14.1", features = ["https"]} 
regex = "1.12.2"
